Homework 4 - [Your team name here]
========================================================


### Task 1 - Scraping LQ

<!-- Detail your approach for scraping La Quinta's data -->

```{r}
load("data/dennys.Rdata")
load("data/lq.Rdata")
lq = na.omit(lq)
```


<br/>

## Task 2 - Scraping Denny's

<!-- Detail your approach for scraping Denny's data -->


<br/>

## Task 3 -  Distance Analysis

<!-- Detail your statistical analysis of the pairwise distance between Denny's and LQ's-->

```{r}
library(geosphere)
library(dplyr)

# distHaversine takes location arguments as (longitude, latitude)
dennysloc = cbind(dennys$Longitude, dennys$Latitude) %>% as.matrix()
lqloc = cbind(lq$long, lq$lat) %>% as.matrix()

dist_mat = apply(dennysloc, 1, function(x) distHaversine(x, lqloc, r = 6378.137))

#for each laquinta, which are the closest dennies
closestDennys = apply(dist_mat, 1, min)

#for each dennys, which are the closest laquintas 
closestlq = apply(dist_mat, 2, min)

plot(ecdf(closestlq), do.points = TRUE, xlim=c(-1, 200), main = "Laquintas Closest to Dennys", xlab = "Distance(km)", ylab = "Proportions for each Distance(%)", col="blue") 

plot(ecdf(closestDennys), xlim=c(-1, 200), main = "Dennys Closest to Laquintas", xlab = "Distance(km)", ylab = "Proportions for each Distance(%)", col="red") 

```
